[project]
name = "instant-transfer"
authors = ["Blockchain Developer"]
description = "A secure and rapid STX transfer protocol"
telemetry = false
requirements = []
[contracts.quick-transfer]
path = "contracts/quick-transfer.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
